lamorel_args:
  log_level: info
  gloo_timeout: 1800
  allow_subgraph_use_whith_gradient: false
  distributed_setup_args:
    n_rl_processes: 1
    n_llm_processes: 1
  accelerate_args:
    config_file: ../configs/accelerate/default_config.yaml
    machine_rank: 0
    main_process_ip: 127.0.0.1
    num_machines: 1
  llm_args:
    model_type: seq2seq
    # model_type: causal
    # model_path: /home/trx/workplace/trx/t5-small
    # model_path: /home/trx/workplace/trx/t5-large/Wojtek/flan-t5-large
    model_path: /home/trx/workplace/trx/t5-base/zimuwangnlp/flan-t5-base
    # model_path: /home/trx/workplace/trx/t5-xl/yiqunchen/flan-t5-xl
    # model_path: /home/trx/workplace/trx/gpt2
    # model_path: /home/trx/workplace/trx/Llama-3.2-1B
    pretrained: true
    minibatch_size: 192
    pre_encode_inputs: true
    load_in_4bit: false
    parallelism:
      use_gpu: true
      model_parallelism_size: 1
      synchronize_gpus_after_scoring: false
      empty_cuda_cache_after_scoring: false
rl_script_args:
  path: ???
  seed: 1
  # ppo
  ppo_epochs: 4
  lam: 0.99
  gamma: 0.99
  lr: 1e-6
  entropy_coef: 0.01
  value_loss_coef: 0.5
  clip_eps: 0.2
  max_grad_norm: 0.5
  minibatch_size: 8
  # llm
  gradient_batch_size: 1
  gradient_minibatch_size:
  # rl training
  max_ep_len: 100
  epochs: 2000
  steps_per_epoch: 192
  save_freq: 50
  test_freq: 2
  output_dir:
  loading_path:
  ## LoRA
  use_cache: true
  use_lora: false
  lora_r: 8
  lora_alpha: 32
  # wandb
  wandb_init: false
  wandb_project:
  wandb_name:
  # macEnv
  number_envs: 2
  ue_num: [2, 3]

  test: false

rl_script_args_test:
  # rl training
  output_dir:
  loading_path:
  ## LoRA
  use_cache: true
  use_lora: false
  lora_r: 8
  lora_alpha: 32
  # wandb
  wandb_init: false
  wandb_project:
  wandb_name:
  # macEnv
  number_envs: 2
  ue_num: [2, 3]
  seed: 1113


  test: true
  test_num: 5

# macEnv_args:
#   rho: 1.5
#   recent_k: 0
#   UE_num:
#   UE_txbuff_len: 20
#   p_SDU_arrival: 0.5
#   tbl_error_rate: 1e-3
#   TTLs: 24
#   UCM: None
#   DCM: None
#   need_comm: true
#   env_name: 'MacPro_Env'

# macEnv_test_args:
#   rho: 1.5
#   recent_k: 0
#   UE_num:
#   UE_txbuff_len: 20
#   p_SDU_arrival: 0.5
#   tbl_error_rate: 1e-3
#   TTLs: 24
#   UCM: None
#   DCM: None
#   need_comm: true
#   env_name: 'MacPro_Env_Test'
#   test_num: 5
#   seed: 1113